# Generated by Django 4.2.28 on 2026-04-04

from django.db import migrations, models


HOST_COUNT_FIELDS = [
    'calc_bug_updates_count',
    'calc_sec_updates_count',
    'local_bug_updates_count',
    'local_phased_deferred_count',
    'local_sec_updates_count',
]


def _get_existing_columns(connection, table_name):
    with connection.cursor() as cursor:
        return {
            col.name for col in connection.introspection.get_table_description(cursor, table_name)
        }


def add_missing_host_count_fields(apps, schema_editor):
    Host = apps.get_model('hosts', 'Host')
    table_name = Host._meta.db_table
    existing_columns = _get_existing_columns(schema_editor.connection, table_name)

    # Some environments may already have one or more columns due to drift or
    # partial rollouts. Add only what is still missing.
    for field_name in HOST_COUNT_FIELDS:
        if field_name in existing_columns:
            continue

        field = models.PositiveIntegerField(default=0, db_index=True)
        field.set_attributes_from_name(field_name)
        schema_editor.add_field(Host, field)


def backfill_local_and_calc_counts(apps, schema_editor):
    Host = apps.get_model('hosts', 'Host')
    table_name = Host._meta.db_table

    # Ensure the physical columns exist even when schema state drifted before
    # this migration is replayed in a fresh test database.
    add_missing_host_count_fields(apps, schema_editor)

    existing_columns = _get_existing_columns(schema_editor.connection, table_name)
    required_columns = set(HOST_COUNT_FIELDS + ['sec_updates_count', 'bug_updates_count'])
    if not required_columns.issubset(existing_columns):
        return

    quoted_table = schema_editor.quote_name(table_name)
    quoted = schema_editor.quote_name
    schema_editor.execute(
        "UPDATE {table} SET {local_sec} = {sec}, {local_bug} = {bug}, {local_phased} = 0, {calc_sec} = {sec}, {calc_bug} = {bug}".format(
            table=quoted_table,
            local_sec=quoted('local_sec_updates_count'),
            sec=quoted('sec_updates_count'),
            local_bug=quoted('local_bug_updates_count'),
            bug=quoted('bug_updates_count'),
            local_phased=quoted('local_phased_deferred_count'),
            calc_sec=quoted('calc_sec_updates_count'),
            calc_bug=quoted('calc_bug_updates_count'),
        )
    )


def reverse_backfill(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0012_backfill_cached_counts'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_missing_host_count_fields, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='host',
                    name='calc_bug_updates_count',
                    field=models.PositiveIntegerField(db_index=True, default=0),
                ),
                migrations.AddField(
                    model_name='host',
                    name='calc_sec_updates_count',
                    field=models.PositiveIntegerField(db_index=True, default=0),
                ),
                migrations.AddField(
                    model_name='host',
                    name='local_bug_updates_count',
                    field=models.PositiveIntegerField(db_index=True, default=0),
                ),
                migrations.AddField(
                    model_name='host',
                    name='local_phased_deferred_count',
                    field=models.PositiveIntegerField(db_index=True, default=0),
                ),
                migrations.AddField(
                    model_name='host',
                    name='local_sec_updates_count',
                    field=models.PositiveIntegerField(db_index=True, default=0),
                ),
            ],
        ),
        migrations.RunPython(backfill_local_and_calc_counts, reverse_backfill),
    ]
