# Generated by Django 4.2.28 on 2026-04-04

from django.db import migrations, models


def backfill_local_and_calc_counts(apps, schema_editor):
    Host = apps.get_model('hosts', 'Host')
    for host in Host.objects.all():
        # Preserve current behavior by seeding both local and calculated values
        # from existing legacy counters.
        host.local_sec_updates_count = host.sec_updates_count
        host.local_bug_updates_count = host.bug_updates_count
        host.local_phased_deferred_count = 0
        host.calc_sec_updates_count = host.sec_updates_count
        host.calc_bug_updates_count = host.bug_updates_count
        host.save(update_fields=[
            'local_sec_updates_count',
            'local_bug_updates_count',
            'local_phased_deferred_count',
            'calc_sec_updates_count',
            'calc_bug_updates_count',
        ])


def reverse_backfill(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0012_backfill_cached_counts'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='calc_bug_updates_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='host',
            name='calc_sec_updates_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='host',
            name='local_bug_updates_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='host',
            name='local_phased_deferred_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='host',
            name='local_sec_updates_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.RunPython(backfill_local_and_calc_counts, reverse_backfill),
    ]
