# Generated by Django 4.2.29 on 2026-04-08 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0013_host_local_and_calc_update_counts'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='last_provider_power_state',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='last_provider_sync_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='provider_account_scope',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='provider_instance_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='provider_machine_id',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='provider_name',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='provider_region',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='provider_resource_group',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='provider_vm_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='provider_zone',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='reconcile_confidence',
            field=models.CharField(db_index=True, default='unknown', max_length=16),
        ),
        migrations.AddField(
            model_name='host',
            name='reconcile_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
