# Generated by Django 4.2.28 on 2026-04-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_alter_report_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='phased_deferred_updates',
            field=models.TextField(blank=True, null=True),
        ),
    ]
