# Generated by GitHub Copilot on 2026-04-06.

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='HostInventorySharedView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Shared view', max_length=255)),
                ('state', models.JSONField(default=dict)),
                ('share_token', models.CharField(db_index=True, editable=False, max_length=64, unique=True)),
                ('manage_token', models.CharField(db_index=True, editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={'ordering': ['name', '-updated_at']},
        ),
    ]