# Generated by GitHub Copilot on 2026-04-06.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0002_alter_hostinventorysharedview_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HostInventorySharedView',
            new_name='HostInventoryHostgroup',
        ),
        migrations.RemoveField(
            model_name='hostinventoryhostgroup',
            name='manage_token',
        ),
        migrations.RemoveField(
            model_name='hostinventoryhostgroup',
            name='share_token',
        ),
        migrations.AlterField(
            model_name='hostinventoryhostgroup',
            name='name',
            field=models.CharField(default='Hostgroup', max_length=255),
        ),
    ]
